### ISSUE TITLE
extend support to non-json files

### ISSUE THREAD

**Issue by ibezkrovnyi** [pnpm/meta-updater#1]
Hi, we are using **meta-updater** for some json files, and this is really powerful and convenient tool, however we are limited to only files with `.json` extension.

We would like to also process the following files in meta-updater:
- `.npmrc`, `.gitignore`, `.browserlistrc` (text content)
- `somefile.cjs`, `prettier.config.js` (js content)
- `.gitlab-ci.yaml` (yaml content)

### JavaScript

And we will definitely know the format for each file, so the simplest change would be to replace the following:
https://github.com/pnpm/meta-updater/blob/4dde93ee877a9210e05ec60684a0f9aac09aa763/src/index.ts#L56-L57

with:
```ts
if (!p.endsWith('.json')) continue
const obj = p.endsWith('.json') ? await readJsonFile(fp) : await readFile(fp, 'utf8')
```
and add `import { readFile } from 'fs/promises'` to the top of file

### Type Checking 
Also `update` parameter can be strongly typed depending if file has or hasn't `.json` extension: [ts playground](https://www.typescriptlang.org/play?#code/PTAEEsFsAcHsCcAuBnUA6DBYAUIgntAKagAK8sAVoQMaICyAhgHbgBmhyioAvKAN4BfANw4QoHBNwFiAYXiEGiQgFVoAE0WEAYgFcm1ADwAVAHw9QAClgAjCgC5QRgDSg14eA87xwTAOYvIZjYORAcyShp6IPZOAEoeMyNQAB9SckhwZEJjFNAmHQAbArNU-KLJfCJQVQ0lAFF4cnhzPhxQUEIADyJaQjUHAHlbSNyvH19csoK20AZaHQYCweHaUcRvP0nC6ex26EUAC0918ZwBSS64JFnkPH1QVj1acFgmUCJ4VgRIGs1kHK6SiYalQACUaAg1AYxn4XHoANZMWAAdyYJhMFhmyIQ8OQ+2ohAAIu5jht-DMdOpNA4+KAANoAaQgb3hhDwsFYjgAug4mYDCMDUAADAAkfBhvgEaAoyFeQtAAH5QHIFEpfkpdPoDDYqLQzA4VZp1dontCTn4zAInDNYNAUAqaaAlJwHaBrLBYAUFG9zthYmF0plslNcsaGk0zK1dqAxBg0DN5IgdPA3iGGKhmHgRNhfTgPl94D8qc7MdGAOQyOwAHXCupQVegTGgkDL1ujUfa7TL+PhDF8hGlsqYZYctQYCTy2xcYgOhHkrkU4-28AYkEISmazDUoETybeADdFjpiAx55ViNRZ9RWWoZl20E3IPBqCObndqE7AROlJ1ENOwLO85ju8p6ruuc6zMCO7rnuoCHgUx6zGe0igJeNA3jMvqxEAA)

**Comment by zkochan** [comment]
It might be even more convenient if we provide a parser/strinigifier for different file types.

**Comment by ibezkrovnyi** [comment]
Do you mean adding support for more types out of the box (I can think of yaml, yml and jsonc  and may be json5) and treat all other file types as pure text ?

**Comment by zkochan** [comment]
either our of the box or passing in the parsers/stringifiers to meta-updater.

**Comment by kevinkhill** [comment]
[I recently discovered this nifty little package that turns out to be very useful](https://mrm.js.org/) and maybe it's powers could be merged into `@pnpm/meta-updater`?

In the last year I've ditched Yarn and adopted PNPM in all my projects. It would be amazing to have the `mrm` file fixing/modding abilities baked into PNPM. Utilizing this meta-updater is really nice for me to make sure everything is synced up.

**Comment by ibezkrovnyi** [comment]
@zkochan Experimented a bit with passing custom format handlers into meta-updater taking into account type safety. Types are flowing everywhere, so minimal typing is required from user.

Types and Custom Formats ('.gitignore' in example below) and Built-in Formats ('json' in example below) are merged.

If this approach will be implemented, it will be possible to add new built-in types into meta-updater anytime later.

Here is what I got: [TS Playground](https://www.typescriptlang.org/play?ts=4.7.4#code/JYWwDg9gTgLgBAbzgBShAVgUwMYwLICGAdsAGaYDO8AvnKWiHAEQACYRYIA9DAJ5iUmAbgBQoSLDgAqOAQp159CIyakKXMA2AVBo8dHhIANhAIATAFIUIRAGLAjmOLSUqT5gLTprRD6QeYwmLgBohwAO5QwDCYVjb2js50DMyR0ZhePn4BQSJcXHAAvMUlpWXlFZUlcACSRDFQRARGcAAq-JRwABbAZmaYRHDAg2wc3CCYMAQeAK5gZgQNRVUrq2tVYvWYUKQE2E4AQnKYttAgiwASxGaOUPIIInBwANqkZ4sAXHBUUUQA5gBdL6nKDnGBXIg3bYAHhmRAA1kQIOEiAA+ETUESbBq7fZwEFgiFQqDQgDCNhi9VRiEecCgmHMAApaU9-I5kIsul8fsM-gAaFlwMzAKDcmC-fmC84kchUL6oDA4fDEMiUGC0gCU8q0OgA8lAAGrNGaYMkUgbwAA+cCIMyMRlRoiecwWMWZTye2HN9S+5K29QFHqFIrFEsDHulqrlKDQWFwhBlavDzp0UAAqvNFiciF8M66TnDsGb-TB0U8tTHlNpMPqjUYTcXKVabXaHU6IlE3YKvSXfd6YMng6LvuLeYPI7KYNrFfGVZPNdOQNXa8bTQA3CC9R0YrF8ARwPNZ2yF6GtamFODuuA9ptfVpwa22+3h4XDnn-cMTtXTuPKxNUEQNSKakFSXPVDVXU8Hxbe1txEPcnFA5cIPrU0zyKNpoKQnRTzghC4AAcUmP0mygzAAA9KTMeQCUua5blhBEkRRVFzzgAA5Gx2NbAgACNHGhWkAEFwgIdIzGhAAlSYZkadoBFPZ4mBdLMmABViRDwjo4CJBjaPBejtnkCiqPkaSvSgCT335fF3gMyEGLhRFkTRViMIeJ5nn0oZBnhTBeAgUhbNBOiHKMoEaSDN4QqnYKwXbZ1MxiXMkoLIgiyImASItaF9N0oyvLs9TtyeahRGoZ4-ICoK8sMu4AVEbFtlxJxDxiXUwBgYAbHuWk2UoL5zOgKzRw-HS6uhA4ZgcMw6lqsK7lY8qsWGHE9la1KOq6nqAHVoi6fSKEEp5SRmKhlHm4ljMogZqLgI4dEu24KE0yK6ACChBpwYboWsvlxoWybpqMWa7Ds-K7jgAAyOBTvOkAnqMpa+rsz7YbOmALvBuqKGWkQeyoOBeOBmA5uxhb5AvDy4AAcm8Gwaa+amnnpJl+o5GAuRHCUgOZj16RgWTBlZywfASTBGXZzkNQS5xBxUrsg09fsvggXjf0HJ5X1DMdBSeL9owVX8EyjAc9bgM7tja7MUvzY90uhNXfzLD1efNgWhYt1NrdsIhGRvC1-tff6DZgGXBWoQc5F4dKO3Sf2VbgJ2lX+qXOZ1-43aV2RROiOOYjiOwAklgIOa6f6A4DMJ+hiXA6n6H04HFE1nHDoNI9pDvaDka8epgUR8KmmayZiiHKabjpAqJkmR8JHHGooiR4FIQttsGbBWZia2tu6ogKCvBWa063e0e34+esA22sx3nrREX0IV-Stfr03zAz7Xo77xM275Aek5yauqiA+m1z57yvu1UBFA9qc0OrhS+B4QEf2gQdVGuE77kSXnQVeu8X4Mi3ogk+jJD43zARbJiLks50hko0C2BDb47jyAUdYzC1gHgoAQP4TgKIEHAI4SmLCBGCJKFiLgUgpCPBkGmdhnC4AAFFyI8LAIkAAjF8AAyuIRIZ0OGYAkVwR499JAE3gP0XYdoYDKIwoycI0B4QUDAOtAAIiGbmvIgKFGpNTD2NCN54LfnQvejI+b9TRnzJ4TAYAUB7P4P4AA6emRAmBM3NqyOyXwmAJKYJrD0h8viMk0JgNc-0AD6wc4DFNDu46kBS1xwAAPxwBqXAZJ2cgz5GzgAPTqSkj0XpwABCgCQ0JTcCBQE4bFJglAiAmSYHLHpHds4LI9Es6g4cyoiLERIthOi5EKN4U4AATF8ZB14MbKDoHZWmsS-jRGAH8JE9IaZCkwP4aZZg9H4z7nAG5XV7nQH-jFdytJo6xxFiXdknIM5-EoSzahgxGQEFzsvCgsSRbi3BZgMu-1lIwFIAADiYBqDUsT7FGGiIyJgAAdRJbc5mJXzFeZWvZXH-GeACaCT4jCDm1iyyUQZQ4-iVCbSc8tvapV9uAtKRZrJspdjCqhgsaGW3TOKv2lcBxDhDnONUtKlkguwPnCW6qoVstTqXSFvL5XGLIcAAAji3C8ZEbqQnkE5ZiRBZUIqgFAAgvA7xVPNkJb1vrYmuEZNM8IcA1GTEUraEAvFtjqS9T63gRKSUGEZLSp4iKxLItiWkGI6K07lxtfao1-ZiXoE3H7KlNLsUzFxQS3VApu7yGMQvDBoRrWmIIOYg5VibFQDsQ4-Yzi3yjWhcBN63j16v3foQ4JqMWlKyYNc25fz6RJO+euh5AKwSDiWayD6y6gwRKiTYGJ8SfBbrCR6aKYJ0mZOyfSrMeSaklLKRU7VVAqmNPpLUupDTb1tIKErLpPTlb9NuEMpmIyxmTHSVMmZdLWmYkWdk1dBSYBdW2Hc3dN6en3s+MwNdvz8PPtofmN9-6P0ihKZUqdTTAMvCYEifoFSIBmDtIIAEFH2mtPA+hiO4ZVnlUavqrBT8cEi0LuisAULKHil4G9WFirBg5rzu4UW8QAiO3VkqIBYBdXXkWNgLol5tjDmIKmlTQwgqMks7Er0-RlgXiYLI9iuoPOtEJbZ1TntOWyzQx6TmaBI2WfbJiTEQA)

## Usage Example 1: Simple usage
```ts
export default (workspaceDir: string) => {
  return createUpdateOptions({
    files: {
      "tsconfig.json": {
        format: "json",
        update: (prev, _dir, _manifest) => prev ? prev : {
          compilerOptions: { target: "esnext" },
        },
      },
    },
  });
};
```

## Usage Example 2: With custom format '.gitignore' defined
```ts
const gitignoreFormat = {
  async read(filePath: string) {
    return (await fs.readFile(filePath, "utf8")).split("\n");
  },
  update(
    content: string[] | null,
    dir: string,
    manifest: ProjectManifest,
    userUpdateFn: UpdateFunc<string[]>
  ) {
    return userUpdateFn(content, dir, manifest);
  },
  async write(content: string[], filePath: string) {
    const unique = <T extends unknown[]>(array: T) =>
      Array.from(new Set<T[number]>(array)).sort();
    await fs.writeFile(filePath, unique(content).join("\n"), "utf8");
  },
} as const;

export default (workspaceDir: string) => {
  return createUpdateOptions({
    formats: {
      ".gitignore": gitignoreFormat,
    },
    files: {
      "tsconfig.json": {
        format: "json",
        update: (prev, _dir, _manifest) => prev ?? {
          compilerOptions: { target: "esnext" },
        }
      },
      ".prettierignore": {
        format: ".gitignore",
        update: (prev, _dir, _manifest) => prev ?? ["node_modules"],
      },
    },
  });
};
```

## Also potentially we could look into template string direction:

Current version of meta-updater defines `'<file>': <update_func>`. 

Because now we need to also pass format, it is now on object: `'<file>': { format: '<format>', update: <update_func> }`.

But actually we can write it much shorter: `'<file> [format]': <update_func>`

```ts
export default (workspaceDir: string) => {
  return createUpdateOptions({
    files: {
      "tsconfig.json [json]": (prev, _dir, _manifest) => prev ? prev : {
          compilerOptions: { target: "esnext" },
       },
    },
  });
};
```

### Also we can add second way of determining format - by defined in `FormatHandler` extension, so usage will look:

This will simplify definition of each file that has clear extension (json/yaml/ts/etc). This won't work with files w/o extension (.gitignore/prettierignore/.eslintrc/etc).

```ts
export default (workspaceDir: string) => {
  return createUpdateOptions({
    files: {
      "tsconfig.json": (prev, _dir, _manifest) => prev ? prev : {
          compilerOptions: { target: "esnext" },
       },
    },
  });
};
```

While `json` format can be defined as following:
```ts
const jsonFormat = {
  extension: '.json', // <-------------------------------------------
  read(filePath: string) {
    return readJsonFile(filePath);
  },
  update(
    content: object,
    dir: string,
    manifest: ProjectManifest,
    userUpdateFn: UpdateFunc<object>
  ) {
    return userUpdateFn(content, dir, manifest);
  },
  async write(content: object, filePath: string) {
    await writeJsonFile(filePath, content, { detectIndent: true });
  },
} as const;
```

**Comment by zkochan** [comment]
Detecting by extension sounds good. And for the rest maybe the format can be specified by the user.
