### ISSUE TITLE
Publish v0.2.0 to npm

### ISSUE THREAD

**Issue by mackermans** [pnpm/meta-updater#6]
Hi @zkochan, I noticed that the version of [@pnpm/meta-updater](https://www.npmjs.com/package/@pnpm/meta-updater) on npm is still at v0.0.6 (a year old now), would you mind publishing the latest v0.2.0?

I'm currently exploring how to automatically generate TypeScript project references in our monorepo – [your implementation](https://github.com/pnpm/pnpm/blob/main/.meta-updater/src/index.ts) seems great, eager to try it out!

**Comment by zkochan** [comment]
Done
